### ISSUE TITLE
样本构造

### ISSUE THREAD

**Issue by wj19971997** [Autumn945/KDDCUP20-Debiasing-Top5#1]
老哥，我想请问一下构造样本的时候是不是滑窗构造的？

**Comment by Autumn945** [comment]
是的，12345，分成1预测2，12预测3，123预测4，1234预测5这样

**Comment by wj19971997** [comment]
好嘞，谢谢老哥


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Autumn945/KDDCUP20-Debiasing-Top5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 中午11:00
收件人:&nbsp;"Autumn945/KDDCUP20-Debiasing-Top5"<KDDCUP20-Debiasing-Top5@noreply.github.com&gt;;
抄送:&nbsp;"、"<1402129410@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Autumn945/KDDCUP20-Debiasing-Top5] 样本构造 (#1)





 
是的，12345，分成1预测2，12预测3，123预测4，1234预测5这样
